import React from 'react';

const LegalDisclaimerPage: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto animate-fade-in text-gray-300">
            <div className="bg-emerald-900/50 p-6 sm:p-8 rounded-2xl border border-green-800 shadow-lg">
                <h1 className="text-3xl sm:text-4xl font-bold text-center text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-yellow-500 mb-6">
                    Legal Disclaimer
                </h1>

                <div className="space-y-6 leading-relaxed text-sm">
                    <p className="font-semibold text-yellow-300">
                        Please read this disclaimer carefully before using the Trade X application. Your use of the application constitutes your agreement to this disclaimer.
                    </p>
                    
                    <h2 className="text-xl sm:text-2xl font-semibold text-yellow-400 border-b-2 border-yellow-700 pb-2">1. No Financial Advice</h2>
                    <p>
                        The information and analysis provided by Trade X, including but not limited to trading signals, market analysis, entry prices, take profit levels, and stop loss levels, are generated by an artificial intelligence model. This information is for informational and educational purposes only and should not be construed as financial, investment, legal, or tax advice. Trade X is not a registered investment advisor or broker-dealer.
                    </p>
                     <p>
                        You should not make any investment decision based solely on the information provided by this application. We strongly recommend that you conduct your own thorough research and consult with a qualified, independent financial advisor before making any investment decisions.
                    </p>

                    <h2 className="text-xl sm:text-2xl font-semibold text-yellow-400 border-b-2 border-yellow-700 pb-2">2. Risk Warning</h2>
                    <p>
                        Trading in financial markets, including forex, commodities, and cryptocurrencies, involves a very high level of risk and is not suitable for all investors. The possibility exists that you could sustain a loss of some or all of your initial investment. Therefore, you should not invest money that you cannot afford to lose. You should be aware of all the risks associated with trading and seek advice from an independent financial advisor if you have any doubts. Past performance is not indicative of future results.
                    </p>

                    <h2 className="text-xl sm:text-2xl font-semibold text-yellow-400 border-b-2 border-yellow-700 pb-2">3. Accuracy of Information</h2>
                    <p>
                        While we strive to provide accurate and timely information, Trade X and its AI models may produce information that is inaccurate, incomplete, or outdated. The AI's analysis is based on historical data and patterns, which do not guarantee future performance or outcomes. We make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the application.
                    </p>

                     <h2 className="text-xl sm:text-2xl font-semibold text-yellow-400 border-b-2 border-yellow-700 pb-2">4. Limitation of Liability</h2>
                    <p>
                        Under no circumstances shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Trade X application or reliance on any information provided on the application. Your use of the application and your reliance on any information on the application is solely at your own risk. You are solely responsible for your own trading decisions, and you agree to hold Trade X and its creators harmless from any and all claims, losses, or liabilities arising from your use of the information provided.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default LegalDisclaimerPage;
